name: paged_datatable
description: A brand new way of creating paginated DataTables in Flutter with sorting and filters
version: 1.4.8
homepage: https://github.com/tomasweigenast/paged-datatable

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  equatable: ^2.0.5
  collection: ^1.17.2
  calendar_date_picker2: ^0.5.3
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.5

flutter:
  generate: true

flutter_intl:
  enabled: true
  class_name: PagedDataTableLocalization
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  use_deferred_loading: false
